CURRENCY_PHP = "Php"
CURRENCY_USD = "Usd"

CURRENCY_OPTIONS = (
    (CURRENCY_PHP,CURRENCY_PHP),
    (CURRENCY_USD,CURRENCY_USD)
)

TYPE_INCOME = "Income"
TYPE_EXPENSE = "Expense"

TYPE_OPTIONS = (
    (TYPE_INCOME,TYPE_INCOME),
    (TYPE_EXPENSE,TYPE_EXPENSE)
)